id: I14BE0DD9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T18:40:13+00:00'
last_modified: '2022-06-07T12:06:41.926067+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12536
  title: མདོ་མང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C0E4:
      image_group_id: I1KG12584
      title: ''
      total_pages: 756
      order: 1
      base_file: C0E4.txt
    C6CC:
      image_group_id: I1KG12588
      title: ''
      total_pages: 756
      order: 2
      base_file: C6CC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
