id: P000519
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12536
  title: མདོ་མང་།
  author: ''
  volumes:
    ac881ec66f334ca9bb497b381d344558:
      image_group_id: I1KG12584
      title: ''
      volume_number: 1
      total_pages: 756
      base_file: v001.txt
    58905b8537f94bc0868497e41f722b56:
      image_group_id: I1KG12588
      title: ''
      volume_number: 2
      total_pages: 756
      base_file: v002.txt
ebook_metadata:
  title: མདོ་མང་།
  author: ''
  sku: P000519
  cover: cover.jpg
  layers:
  - pagination
