id: P000519
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-16 15:44:13.012728
source_metadata:
  id: bdr:W1KG12536
  title: མདོ་མང་།
  author: ''
  volumes:
    ac881ec66f334ca9bb497b381d344558:
      image_group_id: I1KG12584
      title: ''
      volume_number: 1
      total_pages: 756
      base_file: v001.txt
    58905b8537f94bc0868497e41f722b56:
      image_group_id: I1KG12588
      title: ''
      volume_number: 2
      total_pages: 756
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
